apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - image: debian
          name: temporal-server
          command: |
            curl -sSf https://temporal.download/cli.sh | sh
            temporal server start-dev
          ports:
            - containerPort: 7233 # server port
              name: http-port
            - containerPort: 8233 # UI port
              name: http-port