apiVersion: v1
kind: Service
metadata:
  name: temporal-server-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 7233
      targetPort: 7233
    - name: http
      port: 8233
      targetPort: 8233
  selector:
    app: temporal-server
