apiVersion: v1
kind: Service
metadata:
  name: customer-os-webhooks-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10004
      targetPort: 10004
  selector:
    app: customer-os-webhooks
