#!/bin/bash

if [[ $(brew --version) == *"Homebrew"* ]];
    then
        echo "  👍 Homebrew already installed"
    else
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "  ✅ Homebrew install completed."