apiVersion: v1
kind: Service
metadata:
  name: platform-admin-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10005
      targetPort: 10005
  selector:
    app: platform-admin-api
