name: openline
version: git
summary: Openline CLI
description: Openline CLI
grade: stable
confinement: classic

apps:
  openline:
    command: bin/run

architectures:
  - build-on: [amd64, armhf]

stage-snaps:
  - helm
  - docker
  - kubectl

parts:
  openline:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      COMMIT_MSG=$(git log --max-count 1 --pretty="format:%s" | awk '{print $1}')
      CLI_VERSION=$(grep \"version\": packages/cli/package.json | head -n 1 | awk '{print $2}' | tr -d \" | tr -d \,)
      echo "COMMIT_MSG"
      echo $COMMIT_MSG
      echo "CLI_VERSION"
      echo $CLI_VERSION
      if test "$COMMIT_MSG" = "v$CLI_VERSION"; then
        echo "Setting snapcraft version to $COMMIT_MSG"
        snapcraftctl set-version $COMMIT_MSG
      fi
    override-build: |
      set -ex
      # install yarn
      apt-get update
      apt-get install -y curl
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      apt-get update
      apt-get install -y nodejs yarn
      cd packages/cli
      yarn
      yarn pack --filename openline.tar.gz
      mv openline.tar.gz ../..
      cd ../..
      tar xvzf openline.tar.gz
      rmdir ../install
      mv package ../install
      OS=linux ./scripts/utils/_fetch_node_binary ../install/bin
      cd ../install && yarn --prod
      cd ../install && bin/run -v
      sed -i 's/#!\/usr\/bin\/env node/#!\/snap\/openline\/current\/bin\/node/' ../install/bin/run
      sed -i "s/^process\.env\.OPENLINE_UPDATE_INSTRUCTIONS.*$/process.env.OPENLINE_UPDATE_INSTRUCTIONS = 'update with: snap refresh openline'/" ../install/bin/run
      mkdir -p snap/hooks
      cat << EOF > snap/hooks/configure
      #!/bin/sh
      set -e
      export PATH="$SNAP_DATA/bin:$PATH"
      openline update
      EOF
      chmod +x snap/hooks/configure